print('--- Aluguel de carros ---')
dias = float(input('Quantos dias alugados? '))
km = float(input('Quantos Km rodados? '))
valor = (dias * 60) + (km * 0.15)
input(f'O total a pagar é de R${valor:.2f}')